### ISSUE TITLE
Add contrib recipe to Symfony Flex

### ISSUE THREAD

**Issue by simivar** [TheBigBrainsCompany/TbbcMoneyBundle#122]
Symfony Flex recipe is super useful for new developers discovering the bundle but also for ones that already used it for a while. 

My proposition is to create a recipe for TbbcMoneyBundle in [recipes-contrib](https://github.com/symfony/recipes-contrib). I can try to create PR over there but as I am fairly new to this bundle I opened it to discuss what should be there. 

From what I see config files didn't change a lot since version 1.0 of this bundle. My proposition is to create most basic 

```json
// manifest.json

{
    "bundles": {
        "Tbbc\\MoneyBundle\\TbbcMoneyBundle::class": ["all"]
    },
    "copy-from-recipe": {
        "config/": "%CONFIG_DIR%/"
    }
}
```

```yaml
// config/packages/tbbc_money.yml 

tbbc_money:
    currencies: ["USD", "EUR"]
    reference_currency: "EUR"
    decimals: 2
```
