### ISSUE TITLE
Missing argument for tbbc_money.ratio_provider.ecb

### ISSUE THREAD

**Issue by LauLaman** [TheBigBrainsCompany/TbbcMoneyBundle#141]
The V5.0.0 is missing a argument in the service definition (also mentioned [here](https://github.com/TheBigBrainsCompany/TbbcMoneyBundle/pull/136#issuecomment-1132418392) by @baldurrensch)

Error:
```php
In ECBRatioProvider.php line 38:
Tbbc\MoneyBundle\Pair\RatioProvider\ECBRatioProvider::__construct(): Argument #1 ($client) must be of type Symfony\Contracts\HttpClient\HttpClientInterface, Symfony\Component\HttpClient\HttplugClient given, called in /application/var/cache/de_/ContainerXs6RVmb/App_KernelDevDebugContainer.php on line 1324
```

This is because the service definition does not specify the constructor argument:
```xml
<!-- src/Resources/config/services.xml -->
<service id="tbbc_money.ratio_provider.ecb" class="%tbbc_money.ratio_provider.ecb.class%">
</service>
```

Should be:
```xml
<!-- src/Resources/config/services.xml -->
<service id="tbbc_money.ratio_provider.ecb" class="%tbbc_money.ratio_provider.ecb.class%">
     <argument type="service" id="Symfony\Contracts\HttpClient\HttpClientInterface"/>
</service>
```

Fix for now:

Add this to your services.yaml to overwrite the service definition:
```yml
# config/services.yaml

services:
    # ...
  
    tbbc_money.ratio_provider.ecb:
        class: Tbbc\MoneyBundle\Pair\RatioProvider\ECBRatioProvider
        arguments:
            - '@Symfony\Contracts\HttpClient\HttpClientInterface'
```
