### ISSUE TITLE
In Symfony3 the form theming has been changed

### ISSUE THREAD

**Issue by 7system7** [TheBigBrainsCompany/TbbcMoneyBundle#80]
From this:
```yaml
twig:
    form:
        resources:
            - 'TbbcMoneyBundle:Form:fields.html.twig'
```

To this:
```yaml
twig:
    form_themes:
        - 'TbbcMoneyBundle:Form:fields.html.twig'
```

More information if you planning to migrate (also the documentation) to the Symfony3:
http://symfony.com/doc/current/form/form_customization.html
http://symfony.com/doc/current/form/form_themes.html
